# Generated by Django 5.0.2 on 2024-02-17 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_models', '0006_remove_author_birt_date_author_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='harum eligendi ipsa modi possimus deserunt libero necessitatibus provident ab vel quis amet sint ex minus voluptatibus ut non exercitationem'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(default='2017-11-04'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(default='praesentium voluptatem dolorem', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='temporibus officiis quod enim ipsum', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(default='voluptatibus impedit harum unde labore autem reiciendis iste eum eligendi illo at mollitia cumque modi numquam velit excepturi officia esse'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default='1986-05-31'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='accusamus voluptate minima deleniti quis perspiciatis id voluptatem aut optio eius illum repellendus atque cupiditate nisi doloremque consequuntur voluptates odio')),
                ('date_created', models.DateTimeField(default='2023-12-23  12:28')),
                ('date_edited', models.DateField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog_models.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog_models.author')),
            ],
        ),
    ]
