# Generated by Django 5.0.2 on 2024-02-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_models', '0007_alter_article_content_alter_article_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='unde magni delectus commodi quasi porro possimus nobis dolores at itaque ratione recusandae natus dignissimos sint ducimus excepturi sed esse'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(default='2019-09-07'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(default='excepturi quaerat vero', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='dolorem eius quia voluptate inventore', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(default='optio delectus repellendus animi temporibus nulla distinctio beatae vitae quis excepturi deleniti provident quibusdam ab reiciendis maiores dolor veritatis modi'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default='1978-02-18'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='nobis cum ipsum sunt praesentium optio soluta consequatur provident rerum assumenda ipsam quod officia dolores at sed blanditiis quibusdam expedita'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default='2023-11-25 12:41'),
        ),
    ]
