# Generated by Django 5.0.2 on 2024-02-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_models', '0008_alter_article_content_alter_article_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='blanditiis dolorem eveniet repudiandae nesciunt temporibus minima nisi amet placeat adipisci veritatis cum porro eum sed ea ad architecto consequuntur'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(default='2022-05-14'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(default='vel possimus recusandae', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='expedita vel cumque blanditiis aliquid', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(default='perferendis delectus quas architecto aperiam at repellat vel suscipit odit laboriosam culpa soluta quia itaque alias reprehenderit repellendus eos quaerat'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default='2011-04-02'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='sed perferendis molestias excepturi nisi distinctio molestiae dicta dolores impedit earum enim odio mollitia doloribus porro in quasi commodi sit'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default='2023-11-25 14:02'),
        ),
    ]
