# Generated by Django 5.0.2 on 2024-02-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_models', '0009_alter_article_content_alter_article_publication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isPublished',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='dolor labore illo sapiente nemo doloremque dolorem delectus facere animi non voluptatibus accusamus dolores molestiae enim reiciendis quae quod eum'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(default='2019-01-27'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(default='doloribus quidem quos', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='perferendis nobis aliquid nemo qui', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(default='adipisci doloremque eum recusandae sed enim dicta dolorum nostrum temporibus saepe sequi aliquam illo facere sit velit aliquid beatae suscipit'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default='1945-12-09'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='repudiandae provident explicabo sapiente labore harum doloremque officia unde iste aspernatur dolores placeat enim deleniti possimus aliquam maiores ipsa sunt'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default='2023-12-24 21:32'),
        ),
    ]
