# Generated by Django 5.0.2 on 2024-02-28 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_models', '0013_alter_article_content_alter_article_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='cumque harum autem ullam quo laudantium minima laborum quaerat quae dolores deserunt praesentium quidem sit aspernatur porro quod perspiciatis consectetur'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(default='2022-09-14'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(default='odio fuga voluptas', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='quam perspiciatis saepe deleniti ea', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(default='quibusdam non praesentium possimus debitis eaque rem perspiciatis fugiat dignissimos ipsa ut atque veritatis distinctio pariatur id ipsum nesciunt itaque'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default='2008-07-09'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='voluptas inventore praesentium autem explicabo quis ullam eaque ipsa odio rem dolorem labore nisi recusandae laudantium iusto eveniet saepe minima'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 6, 55, 39, 184070)),
        ),
    ]
