# Generated by Django 5.0.2 on 2024-02-17 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Excepturi Deserunt', max_length=100)),
                ('mail', models.EmailField(default='vel@animi.{lorem_ipsum.words(1, common=False)}', max_length=100)),
                ('phone', models.CharField(default='994-164-313', max_length=30)),
                ('path', models.CharField(default='delectus veritatis68, ap.8 ', max_length=200)),
                ('date_reg', models.DateField(default='2022-04-24')),
            ],
        ),
        migrations.CreateModel(
            name='Ware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Veritatis Explicabo', max_length=100)),
                ('notes', models.CharField(default='Nesciunt Perspiciatis Aspernatur Eos', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=13732.59, max_digits=9)),
                ('quantity', models.IntegerField(default=16)),
                ('date_income', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('date_locked', models.DateField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.client')),
                ('wares', models.ManyToManyField(blank=True, default=[], to='models.ware')),
            ],
        ),
    ]
