# Generated by Django 5.0.2 on 2024-02-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_client_date_reg_alter_client_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_reg',
            field=models.DateField(default='2000-04-15'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail',
            field=models.EmailField(default='provident@delectus.vero', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='Maxime Autem', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='path',
            field=models.CharField(default='nam similique19, ap.63 ', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='975-985-438', max_length=30),
        ),
        migrations.AlterField(
            model_name='ware',
            name='notes',
            field=models.CharField(default='Mollitia Possimus Cumque Necessitatibus', max_length=100),
        ),
        migrations.AlterField(
            model_name='ware',
            name='price',
            field=models.DecimalField(decimal_places=3, default=1617.42, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ware',
            name='quantity',
            field=models.IntegerField(default=63),
        ),
        migrations.AlterField(
            model_name='ware',
            name='title',
            field=models.CharField(default='Laudantium Libero', max_length=100),
        ),
    ]
