# Generated by Django 5.0.2 on 2024-02-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_remove_order_front_view_ware_front_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_reg',
            field=models.DateField(default='2023-08-27'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail',
            field=models.EmailField(default='quasi@doloremque.quis', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='Repudiandae Nesciunt', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='path',
            field=models.CharField(default='recusandae totam7, ap.47 ', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='129-033-373', max_length=30),
        ),
        migrations.AlterField(
            model_name='ware',
            name='front_view',
            field=models.ImageField(help_text='front view', null=True, upload_to='front_views/'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='notes',
            field=models.CharField(default='Id Ipsa Odio Consectetur', max_length=100),
        ),
        migrations.AlterField(
            model_name='ware',
            name='price',
            field=models.DecimalField(decimal_places=3, default=88150.03, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ware',
            name='quantity',
            field=models.IntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='ware',
            name='title',
            field=models.CharField(default='Officia Pariatur', max_length=100),
        ),
    ]
