# Generated by Django 5.0.2 on 2024-02-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_client_date_reg_alter_client_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='front_view',
            field=models.ImageField(height_field=720, help_text='front view', null=True, upload_to='front_views/', width_field=1080),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_reg',
            field=models.DateField(default='2007-09-26'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail',
            field=models.EmailField(default='voluptatem@ipsum.pariatur', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='Voluptas Repellat', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='path',
            field=models.CharField(default='inventore perspiciatis77, ap.34 ', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='420-898-256', max_length=30),
        ),
        migrations.AlterField(
            model_name='ware',
            name='notes',
            field=models.CharField(default='Modi Officia Distinctio Sunt', max_length=100),
        ),
        migrations.AlterField(
            model_name='ware',
            name='price',
            field=models.DecimalField(decimal_places=3, default=1942.18, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ware',
            name='quantity',
            field=models.IntegerField(default=54),
        ),
        migrations.AlterField(
            model_name='ware',
            name='title',
            field=models.CharField(default='Illum Vitae', max_length=100),
        ),
    ]
