# Generated by Django 5.0.2 on 2024-02-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_client_date_reg_alter_client_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_reg',
            field=models.DateField(default='2009-03-07'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail',
            field=models.EmailField(default='sed@vero.fuga', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='Perferendis Excepturi', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='path',
            field=models.CharField(default='dolor earum45, ap.37 ', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='702-944-584', max_length=30),
        ),
        migrations.AlterField(
            model_name='ware',
            name='notes',
            field=models.CharField(default='Eos Laudantium Dolore Fugit', max_length=100),
        ),
        migrations.AlterField(
            model_name='ware',
            name='price',
            field=models.DecimalField(decimal_places=3, default=27240.08, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ware',
            name='quantity',
            field=models.IntegerField(default=53),
        ),
        migrations.AlterField(
            model_name='ware',
            name='title',
            field=models.CharField(default='Praesentium Commodi', max_length=100),
        ),
    ]
