# Generated by Django 5.0.2 on 2024-02-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_alter_client_date_reg_alter_client_mail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='front_view',
        ),
        migrations.AddField(
            model_name='ware',
            name='front_view',
            field=models.ImageField(height_field=720, help_text='front view', null=True, upload_to='front_views/', width_field=1080),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_reg',
            field=models.DateField(default='2003-10-05'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail',
            field=models.EmailField(default='commodi@veritatis.ducimus', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='Quod Nisi', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='path',
            field=models.CharField(default='ad minus99, ap.74 ', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='198-146-541', max_length=30),
        ),
        migrations.AlterField(
            model_name='ware',
            name='notes',
            field=models.CharField(default='Dignissimos Pariatur Quae Hic', max_length=100),
        ),
        migrations.AlterField(
            model_name='ware',
            name='price',
            field=models.DecimalField(decimal_places=3, default=13872.07, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ware',
            name='quantity',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='ware',
            name='title',
            field=models.CharField(default='Quisquam Nam', max_length=100),
        ),
    ]
