# Generated by Django 5.0.2 on 2024-02-16 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('birt_date', models.DateField(verbose_name='1967-02-03')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='dolores ullam voluptates quia labore', max_length=200)),
                ('content', models.TextField(verbose_name='placeat voluptatibus laboriosam eveniet nisi a repellat nostrum quod sequi ratione vel explicabo maiores ad sint accusantium laudantium commodi temporibus')),
                ('publication_date', models.DateField(verbose_name='2020-09-04')),
                ('tags', models.CharField(default='soluta ab dolor', max_length=100)),
                ('views', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_models.author')),
            ],
        ),
    ]
