# Generated by Django 5.0.2 on 2024-02-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_models', '0003_author_full_name_alter_article_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='ut eaque delectus magni modi assumenda perferendis molestias quidem labore eius tempore aut expedita ducimus nam accusantium fuga error iure'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(verbose_name='2018-08-10'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(default='consectetur laboriosam tempora', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='ratione rem dignissimos rerum minus', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(default='delectus mollitia ipsam dolores pariatur esse deserunt nesciunt nisi placeat laboriosam exercitationem sequi repellat minus quis reiciendis quibusdam fuga odit'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birt_date',
            field=models.DateField(default='1992-11-06'),
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
