# Generated by Django 5.0.2 on 2024-02-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_models', '0005_alter_article_content_alter_article_publication_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='birt_date',
        ),
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default='1996-07-13'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='delectus facilis quis ratione nostrum maxime tenetur quisquam voluptatem minima unde ducimus dolores totam excepturi doloribus iusto placeat distinctio repellat'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(default='2018-12-29'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(default='harum natus numquam', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='voluptas nulla in cupiditate dicta', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(default='similique possimus a sit omnis eum ullam pariatur sequi voluptate repellat quasi esse soluta reiciendis dolorum ratione nulla consectetur reprehenderit'),
        ),
    ]
