# Generated by Django 5.0.2 on 2024-02-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_models', '0010_article_ispublished_alter_article_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='asperiores unde blanditiis perspiciatis molestias quasi accusamus sit dolor maiores commodi deserunt natus magni quia veniam rem cupiditate perferendis necessitatibus'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(default='2018-01-29'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(default='labore pariatur eius', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='vero maiores amet neque esse', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(default='neque accusamus tenetur ipsum obcaecati laudantium repellendus ad nostrum exercitationem natus velit vero voluptatum assumenda ullam fugit molestias adipisci error'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default='1947-10-13'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='numquam aliquid voluptate aspernatur quam debitis maxime ipsam dolore soluta quis necessitatibus accusantium vero commodi quae earum velit reprehenderit enim'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default='2023-11-27 06:04'),
        ),
    ]
