# Generated by Django 5.0.2 on 2024-02-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_models', '0012_alter_article_content_alter_article_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='ullam deleniti eaque quidem voluptates quae amet animi porro sapiente quasi cumque velit tempora fuga aperiam ea possimus beatae illo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(default='2019-10-12'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(default='quod sed mollitia', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='est fugit nobis numquam ratione', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(default='aperiam sint fugiat iusto reprehenderit quam provident quos error qui enim similique perspiciatis iste illo earum ut temporibus voluptatem consectetur'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default='1989-03-11'),
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='quia ratione esse aspernatur laboriosam laudantium consectetur debitis praesentium dolore ex commodi inventore nostrum atque dignissimos dolor porro totam voluptatem'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default='2023-12-02 17:48'),
        ),
    ]
