# Generated by Django 5.0.2 on 2024-02-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_reg',
            field=models.DateField(default='2011-07-24'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail',
            field=models.EmailField(default='veritatis@ipsa.{lorem_ipsum.words(1, common=False)}', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='Doloremque Quibusdam', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='path',
            field=models.CharField(default='in ducimus84, ap.92 ', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='684-000-445', max_length=30),
        ),
        migrations.AlterField(
            model_name='ware',
            name='notes',
            field=models.CharField(default='Facilis Asperiores Sed Accusamus', max_length=100),
        ),
        migrations.AlterField(
            model_name='ware',
            name='price',
            field=models.DecimalField(decimal_places=3, default=55147.36, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ware',
            name='quantity',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='ware',
            name='title',
            field=models.CharField(default='Debitis Cupiditate', max_length=100),
        ),
    ]
